### ISSUE TITLE
Vertical stripes on the text

### ISSUE THREAD

**Issue by pdemidyuk-ib** [theHEXstyle/font2bytes#1]
Hi!

First of all, thank you for your repo! 

I have an issue with font36 from the output library - the text on display has vertical strips, like this:

<img width="530" alt="36" src="https://github.com/user-attachments/assets/a2c12e9e-1dee-4bf1-81f8-c240046aed3d">

I've tried to generate my own cpp fonts, but the issue still persists.

<img width="515" alt="Screenshot at Sep 11 07-23-41" src="https://github.com/user-attachments/assets/27904240-25be-45a1-ba06-e3a981abf22c">

Please suggest

**Comment by theHEXstyle** [comment]
Thanks! You are right. I can replicate the issue.
Just give me a moment to understand it better and release a new version!

**Comment by theHEXstyle** [comment]
Hi, I have updated the code. Thanks for spotting the defect.
Also, I have update the script to better render large characters (for example, the capital M was slightly truncated)
P.s.  I have also created a new repo [bytes2font](https://github.com/theHEXstyle/bytes2font/tree/main) for a quick preview of the font (just to make sure that is properly encoded)
